import numpy as np
import networkx as nx
from scipy.stats import skewnorm
import json


"""
A file to generate standard graph instances with given weight distribution skewness
for testing and comparison between adapt-Clifford and classical algorithms. 

An adjacency matrix is generated by sampling values from a distribution with given moments.
"""

json_dic = {}

for N in [24, 26, 28, 30]:
    ### Only the upper triangular matrix is filled.
    ### The whole matrix is generated by the sum of the upper tri. matrix and its transpose.
    utri_indices = (N*(N-1))/2

    l_indices = np.tril_indices(N, k=-1)

    x = np.linspace(0, int(utri_indices), int(utri_indices)) 

    arr = np.zeros((N, N))

    json_dic["N_{}".format(N)] = {}

    for s in np.arange(-2.0, 2.0, 0.5):

        s = np.round(s, 1)
        json_dic["N_{}".format(N)]["s_{}".format(s)]={}
        
        for it in range(0, 101):
            ### Generate de skewed weight distribution
            ### The distribution is displaced by a constant 10 to avoid negative weights.
            w = skewnorm.rvs(s, 3, 5, size=int(utri_indices))+10  

            arr[l_indices] = w

            adj_mat = arr + arr.T

            adj_mat = np.array(adj_mat)

            G = nx.from_numpy_array(adj_mat)

            adj_data = nx.adjacency_data(G)

            json_dic["N_{}".format(N)]["s_{}".format(s)]["it_{}".format(it)] = adj_data

            print(json_dic.keys())

with open("skewed_w_dist_gi_24_30.json", "w") as outfile:
    json.dump(json_dic, outfile)
